version: "3.7"

services:
  frontend:
    image: "frontend"
    restart: unless-stopped
    networks:
      - default
  backend:
    image: "backend"
    restart: unless-stopped
    networks:
      - default
  nginx_mine:
    image: "nginx"
    restart: unless-stopped
    ports:
      - "80:80"
      - "3000:3000"
    depends_on:
      - frontend
      - backend
networks:
  default:
    name: minesweeper-network
