version: "3.7"

services:
  postgres:
    image: postgres:15.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - ./.env.local.db
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: yarn dev
    depends_on:
      - postgres
    networks:
      - default
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
    volumes:
      - ./frontend:/app/core
      - ./lib:/app/lib
    ports:
      - 5173:5173
    command: yarn dev
    networks:
      - default
  # nginx_mine:
  #   image: "nginx"
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  #   depends_on:
  #     - frontend
  #     - backend
networks:
  default:
    name: minesweeper-network
volumes:
  postgres_data:
