version: "3.7"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.local
    volumes:
      - ./frontend:/app
    ports:
      - 5173:5173
    command: yarn dev
    networks:
      - default
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile.local
    ports:
      - 3000:3000
    volumes:
      - ./backend:/app
    command: yarn dev
    networks:
      - default
  # nginx_mine:
  #   image: "nginx"
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "3000:3000"
  #   depends_on:
  #     - frontend
  #     - backend
networks:
  default:
    name: minesweeper-network
